import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Super Dope Portfolio</title>
        <meta name="description" content="Generated by me, because I am a coder!" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>My Portfolio</h1>

    </div>
  )
}
